name: Build and Deploy MERN App to Minikube

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Environment
        shell: cmd
        run: |
          echo "Operating System:"
          ver
          echo "Shell:"
          echo %COMSPEC%
          echo "Minikube Version:"
          minikube version
          echo "Docker Version:"
          docker --version

      - name: Start Minikube
        shell: cmd
        run: |
          minikube start --driver=docker
          minikube status

      - name: Set up Docker to use Minikube's environment
        shell: cmd
        run: |
          for /f "tokens=*" %i in ('minikube -p minikube docker-env') do %i

      - name: Build Frontend Docker image
        shell: cmd
        run: |
          cd frontend
          docker build -t abdullah577/mern-frontend:latest .

      - name: Build Backend Docker image
        shell: cmd
        run: |
          cd backend
          docker build -t abdullah577/mern-backend:latest .

      - name: Login to Docker Hub
        shell: cmd
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo %DOCKER_PASSWORD% | docker login -u %DOCKER_USERNAME% --password-stdin

      - name: Push Frontend image to Docker Hub
        shell: cmd
        run: docker push abdullah577/mern-frontend:latest

      - name: Push Backend image to Docker Hub
        shell: cmd
        run: docker push abdullah577/mern-backend:latest

      - name: Deploy to Minikube
        shell: cmd
        run: |
          kubectl create namespace scd-project --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/mongo.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Verify deployment
        shell: cmd
        run: |
          kubectl get pods -n scd-project
          kubectl get svc -n scd-project

      - name: Get Frontend URL
        shell: cmd
        run: |
          for /f "tokens=*" %i in ('minikube ip') do set IP=%i
          for /f "tokens=*" %j in ('kubectl get svc frontend-service -n scd-project -o=jsonpath="{.spec.ports[0].nodePort}"') do set PORT=%j
          echo Frontend is accessible at: http://%IP%:%PORT%