name: Build and Deploy MERN App to Minikube

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          eval $(minikube -p minikube docker-env)

      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t abdullah577/mern-frontend:latest .

      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t abdullah577/mern-backend:latest .

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$env:DOCKER_PASSWORD" | docker login -u "$env:DOCKER_USERNAME" --password-stdin

      - name: Push Frontend image to Docker Hub
        run: docker push abdullah577/mern-frontend:latest

      - name: Push Backend image to Docker Hub
        run: docker push abdullah577/mern-backend:latest

      - name: Deploy to Minikube
        run: |
          kubectl create namespace scd-project --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/mongo.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Verify deployment
        run: |
          kubectl get pods -n scd-project
          kubectl get svc -n scd-project

      - name: Get Frontend URL
        run: |
         ip=$(minikube ip)
         port=$(kubectl get svc frontend-service -n scd-project -o=jsonpath="{.spec.ports[0].nodePort}")
         url="http://$ip:$port"
         echo "✅ Frontend is accessible at: $url"
